# Generated by Django 3.0.11 on 2021-01-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('color', models.CharField(max_length=225)),
                ('tile_count', models.IntegerField(default=0)),
            ],
        ),
    ]
