# Generated by Django 3.0.11 on 2021-01-07 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Turn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_turn', to='players.Player')),
            ],
        ),
    ]
